queue_rules:
  - name: highprio
    queue_conditions:
      - label=high

  - name: default
    queue_conditions:
      - label=default

  - name: lowprio
    queue_conditions:
      - label=low

pull_request_rules:

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
    actions:
      queue:

  - name: ask developers to review for a trusted author
    conditions:
      - label=ready
    actions:
      request_reviews:
        users:
          - lecrepont02

  - name: label and comment on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
      comment:
        message: Conflict! The full name of the head repository is {{ head_repo_full_name }}

  - name: dispatch gha workflow on conflicts
    conditions:
      - conflict
      - files=poetry.lock
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: conflicts_resolver.yaml
              inputs:
                head-repo: "{{ head_repo_full_name }}"
                head-branch: "{{ head }}"
                base-branch: main
priority_rules:
  - name: priority for queue `highprio`
    conditions:
      - label=high
    priority: 2500
  - name: priority for queue `default`
    conditions:
      - label=default
    priority: 2250
